version: '3.3'
services:
  database:
    container_name: mysql-envers
    image: mysql:8.0.16
    volumes:
      - "./data/mysql-dev2:/var/lib/mysql-envers-docker"
    # restart: always
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: Welcome123
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

