version: '3.9'

services:

  postgres:
      container_name: 'postgres-envers'
      hostname: postgres
      image: postgres:alpine
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres


